menu_items = [
  {:name => 'Tandoori Chicken Half', :price => 120, :category => 'Bar-be-que'},
  {:name => 'Tandoori Chicken Full', :price => 230, :category => 'Bar-be-que'},
  {:name => 'Afghani Chicken Half', :price => 120, :category => 'Bar-be-que'},
  {:name => 'Afghani Chicken Full', :price => 230, :category => 'Bar-be-que'},
  {:name => 'Chicken Masala Tikka (10pcs.)', :price => 170 , :category => 'Bar-be-que'},
  {:name => 'Chicken Malai Tikka (10pcs.)', :price => 180, :category => 'Bar-be-que'},
  {:name => 'Reshmi Kabab', :price => 200, :category => 'Bar-be-que'},
  {:name => 'Chicken Tangri (4pcs.)', :price => 200, :category => 'Bar-be-que'},
  {:name => 'Mutton Burra (5pcs.)', :price => 200, :category => 'Bar-be-que'},
  {:name => 'Mutton Seekh Kabab (2pcs.)', :price => 170, :category => 'Bar-be-que'},
  {:name => 'Chicken Seekh Kabab (2pcs.)', :price => 180, :category => 'Bar-be-que'},
  {:name => 'GPS SPL Batte Ka Chicken (6pcs.)', :price => 280, :category => 'Chicken'},
  {:name => 'GPS Chicken Punjabi Tarka Quater', :price => 130 , :category => 'Chicken'},
  {:name => 'GPS Chicken Punjabi Tarka Half', :price => 220, :category => 'Chicken'},
  {:name => 'GPS Chicken Punjabi Tarka Full', :price => 360, :category => 'Chicken'},
  {:name => 'Butter Chicken Quater', :price => 110, :category => 'Chicken'},
  {:name => 'Butter Chicken Half', :price => 200, :category => 'Chicken'},
  {:name => 'Butter Chicken Full', :price => 320, :category => 'Chicken'},
  {:name => 'Tawa Chicken Quater', :price => 110, :category => 'Chicken'},
  {:name => 'Tawa Chicken Half', :price => 200, :category => 'Chicken'},
  {:name => 'Tawa Chicken Full', :price => 320, :category => 'Chicken'},
  {:name => 'Chicken Rogani Spl Quater', :price => 120, :category => 'Chicken'},
  {:name => 'Chicken Rogani Spl Half', :price => 220, :category => 'Chicken'},
  {:name => 'Chicken Rogani Spl Full', :price => 340, :category => 'Chicken'},
  {:name => 'Kadai Chicken Spl Quater', :price => 120, :category => 'Chicken'},
  {:name => 'Kadai Chicken Spl Half', :price => 220, :category => 'Chicken'},
  {:name => 'Kadai Chicken Spl Full', :price => 340, :category => 'Chicken'},
  {:name => 'GPS Paneer Punjabi Tarka', :price => 120, :category => 'Veg'},
  {:name => 'Paneer Peshwari', :price => 120, :category => 'Veg'},
  {:name => 'Sahi Paneer', :price => 120, :category => 'Veg'},
  {:name => 'Palak Paneer', :price => 120, :category => 'Veg'},
  {:name => 'Karahi Paneer', :price => 120, :category => 'Veg'},
  {:name => 'Paneer Butter Masala', :price => 120, :category => 'Veg'},
  {:name => 'Paneer Lababdar', :price => 140, :category => 'Veg'},
  {:name => 'GPS Spl Dal Makhani', :price => 90, :category => 'Veg'},
  {:name => 'Chicken Biryani Takatak Full', :price => 120, :category => 'Khushbu-e-Basmati'},
  {:name => 'Chicken Biryani Takatak Half', :price => 240, :category => 'Khushbu-e-Basmati'},
  {:name => 'Mutton Biryani Takatak Full', :price => 120, :category => 'Khushbu-e-Basmati'},
  {:name => 'Mutton Biryani Takatak Half', :price => 240, :category => 'Khushbu-e-Basmati'},
  {:name => 'Spl Veg Biryani Half', :price => 80, :category => 'Khushbu-e-Basmati'},
  {:name => 'Spl Veg Biryani Full', :price => 160, :category => 'Khushbu-e-Basmati'},
  {:name => 'Plain Rice', :price => 50, :category => 'Khushbu-e-Basmati'},
  {:name => 'Zeera Rice', :price => 50, :category => 'Khushbu-e-Basmati'},
  {:name => 'All Time Rajma Rice', :price => 50, :category => 'Khushbu-e-Basmati'},
  {:name => 'Veg Salad Mix', :price => 50, :category => 'Khushbu-e-Basmati'},
  {:name => 'Raita', :price => 40, :category => 'Khushbu-e-Basmati'},
  {:name => 'Boondi', :price => 40, :category => 'Khushbu-e-Basmati'},
  {:name => 'Pudhina', :price => 40, :category => 'Khushbu-e-Basmati'},
  {:name => 'Papad', :price => 10, :category => 'Khushbu-e-Basmati'},
  {:name => 'GPS Veg Thali', :price => 60, :category => 'Khushbu-e-Basmati'},
  {:name => 'GPS Non Veg Thali', :price => 110, :category => 'Khushbu-e-Basmati'},
  {:name => 'Paneer tikka', :price => 150, :category => 'Veg'},
  {:name => 'Tandoori Bharwan Aloo', :price => 150, :category => 'Veg'},
  {:name => 'Paneer Tikka Malai', :price => 180, :category => 'Veg'},
  {:name => 'GPS Soya Tikka', :price => 150, :category => 'Veg'},
  {:name => 'Chilly Chicken Dry/Gravy Half', :price => 150, :category => 'China-To-India'},
  {:name => 'Chilly Chicken Dry/Gravy Full', :price => 300, :category => 'China-To-India'},
  {:name => 'Chilly Paneer Dry/Gravy Half', :price => 150, :category => 'China-To-India'},
  {:name => 'Chilly Paneer Dry/Gravy Full', :price => 300, :category => 'China-To-India'},
  {:name => 'Chilly Potato Dry', :price => 120, :category => 'China-To-India'},
  {:name => 'Veg Chowmein', :price => 80, :category => 'China-To-India'},
  {:name => 'Fried Rice', :price => 80, :category => 'China-To-India'},
  {:name => 'Mutton Rogangosh Half', :price => 150, :category => 'Mutton'},
  {:name => 'Mutton Rogangosh Full', :price => 300, :category => 'Mutton'},
  {:name => 'GPS Mutton Punjabi Taka Half', :price => 150, :category => 'Mutton'},
  {:name => 'GPS Mutton Punjabi Taka Full', :price => 300, :category => 'Mutton'},
  {:name => 'Mutton Keema Wala Half', :price => 170, :category => 'Mutton'},
  {:name => 'Mutton Keema Wala Full', :price => 340, :category => 'Mutton'},
  {:name => 'Keema Kalegi Half', :price => 170, :category => 'Mutton'},
  {:name => 'Keema Kalegi Full', :price => 340, :category => 'Mutton'},
  {:name => 'Yellow Dal Tarka', :price => 80, :category => 'Veg'},
  {:name => 'Pindi Chole', :price => 80, :category => 'Veg'},
  {:name => 'Chingwala Aloo', :price => 100, :category => 'Veg'},
  {:name => 'Aloo Punjabi Tarka', :price => 90, :category => 'Veg'},
  {:name => 'GPS Mix Veg', :price => 100, :category => 'Veg'},
  {:name => 'Soya Chap Masala', :price => 120, :category => 'Veg'},
  {:name => 'Egg Curry', :price => 100, :category => 'Egg'},
  {:name => 'Bhujia', :price => 100, :category => 'Egg'},
  {:name => 'Tandoori Roti', :price => 7, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Butter Roti', :price => 12, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Rumali Roti', :price => 15, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Plain Naan', :price => 10, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Butter Naan', :price => 20, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Laacha Prantha', :price => 20, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Ajjwani Prantha', :price => 20, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Gobi Prantha', :price => 25, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Pyaaz Prantha', :price => 25, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Aloo Prantha', :price => 25, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Keema Prantha', :price => 60, :category => 'Naan Roti/ Saath Saath'},
  {:name => 'Spl Chole Bhature', :price => 30, :category => 'Veg'}
]

menu_items.each do |menu_item|
  Menu.create menu_item
end
